dave@RUPC:~$ which python3
/home/dave/anaconda3/bin/python3
dave@RUPC:~$ python3 --Version
Unknown option: --
usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
dave@RUPC:~$ python3 -h
usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Options and arguments (and corresponding environment variables):
-b     : issue warnings about str(bytes_instance), str(bytearray_instance)
         and comparing bytes/bytearray with str. (-bb: issue errors)
-B     : don't write .pyc files on import; also PYTHONDONTWRITEBYTECODE=x
-c cmd : program passed in as string (terminates option list)
-d     : debug output from parser; also PYTHONDEBUG=x
-E     : ignore PYTHON* environment variables (such as PYTHONPATH)
-h     : print this help message and exit (also --help)
-i     : inspect interactively after running script; forces a prompt even
         if stdin does not appear to be a terminal; also PYTHONINSPECT=x
-I     : isolate Python from the user's environment (implies -E and -s)
-m mod : run library module as a script (terminates option list)
-O     : optimize generated bytecode slightly; also PYTHONOPTIMIZE=x
-OO    : remove doc-strings in addition to the -O optimizations
-q     : don't print version and copyright messages on interactive startup
-s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE
-S     : don't imply 'import site' on initialization
-u     : unbuffered binary stdout and stderr, stdin always buffered;
         also PYTHONUNBUFFERED=x
         see man page for details on internal buffering relating to '-u'
-v     : verbose (trace import statements); also PYTHONVERBOSE=x
         can be supplied multiple times to increase verbosity
-V     : print the Python version number and exit (also --version)
         when given twice, print more information about the build
-W arg : warning control; arg is action:message:category:module:lineno
         also PYTHONWARNINGS=arg
-x     : skip first line of source, allowing use of non-Unix forms of #!cmd
-X opt : set implementation-specific option
file   : program read from script file
-      : program read from stdin (default; interactive mode if a tty)
arg ...: arguments passed to program in sys.argv[1:]

Other environment variables:
PYTHONSTARTUP: file executed on interactive startup (no default)
PYTHONPATH   : ':'-separated list of directories prefixed to the
               default module search path.  The result is sys.path.
PYTHONHOME   : alternate <prefix> directory (or <prefix>:<exec_prefix>).
               The default module search path uses <prefix>/pythonX.X.
PYTHONCASEOK : ignore case in 'import' statements (Windows).
PYTHONIOENCODING: Encoding[:errors] used for stdin/stdout/stderr.
PYTHONFAULTHANDLER: dump the Python traceback on fatal errors.
PYTHONHASHSEED: if this variable is set to 'random', a random value is used
   to seed the hashes of str, bytes and datetime objects.  It can also be
   set to an integer in the range [0,4294967295] to get hash values with a
   predictable seed.
PYTHONMALLOC: set the Python memory allocators and/or install debug hooks
   on Python memory allocators. Use PYTHONMALLOC=debug to install debug
   hooks.
dave@RUPC:~$ python3 -V
Python 3.6.3 :: Anaconda custom (64-bit)
dave@RUPC:~$ cd DjangoProjects
dave@RUPC:~/DjangoProjects$ ls
anaconda_testing  dj_rest_framework
dave@RUPC:~/DjangoProjects$ cd anaconda_testing
dave@RUPC:~/DjangoProjects/anaconda_testing$ git remote -v
fatal: Not a git repository (or any of the parent directories): .git
dave@RUPC:~/DjangoProjects/anaconda_testing$ python3 -V
Python 3.6.3 :: Anaconda custom (64-bit)
dave@RUPC:~/DjangoProjects/anaconda_testing$ conda -h
usage: conda [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    info         Display information about current conda install.
    help         Displays a list of available conda commands and their help
                 strings.
    list         List linked packages in a conda environment.
    search       Search for packages and display their information. The input
                 is a Python regular expression. To perform a search with a
                 search string that starts with a -, separate the search from
                 the options with --, like 'conda search -- -h'. A * in the
                 results means that package is installed in the current
                 environment. A . means that package is not installed but is
                 cached in the pkgs directory.
    create       Create a new conda environment from a list of specified
                 packages.
    install      Installs a list of packages into a specified conda
                 environment.
    update       Updates conda packages to the latest compatible version. This
                 command accepts a list of package names and updates them to
                 the latest versions that are compatible with all other
                 packages in the environment. Conda attempts to install the
                 newest versions of the requested packages. To accomplish
                 this, it may update some packages that are already installed,
                 or install additional packages. To prevent existing packages
                 from updating, use the --no-update-deps option. This may
                 force conda to install older versions of the requested
                 packages, and it does not prevent additional dependency
                 packages from being installed. If you wish to skip dependency
                 checking altogether, use the '--force' option. This may
                 result in an environment with incompatible packages, so this
                 option must be used with great caution.
    upgrade      Alias for conda update. See conda update --help.
    remove       Remove a list of packages from a specified conda environment.
    uninstall    Alias for conda remove. See conda remove --help.
    config       Modify configuration values in .condarc. This is modeled
                 after the git config command. Writes to the user .condarc
                 file (/home/dave/.condarc) by default.
    clean        Remove unused packages and caches.
    package      Low-level conda package utility. (EXPERIMENTAL)

optional arguments:
  -h, --help     Show this help message and exit.
  -V, --version  Show the conda version number and exit.

other commands, such as "conda build", are available when additional conda
packages (e.g. conda-build) are installed

dave@RUPC:~/DjangoProjects/anaconda_testing$ conda list
# packages in environment at /home/dave/anaconda3:
#
_license                  1.1                      py36_1  
aiohttp                   2.2.3                     <pip>
alabaster                 0.7.10                   py36_0  
anaconda                  custom                   py36_0  
anaconda-client           1.6.3                    py36_0  
anaconda-navigator        1.6.2                    py36_0  
anaconda-project          0.6.0                    py36_0  
antiorm                   1.2.1                     <pip>
appdirs                   1.4.3                     <pip>
asn1crypto                0.22.0                   py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3.2               np112py36_0  
async-timeout             1.2.1                     <pip>
babel                     2.4.0                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.6.0                    py36_0  
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bleach                    1.5.0                    py36_0  
bokeh                     0.12.5                   py36_1  
boto                      2.46.1                   py36_0  
bottleneck                1.2.1               np112py36_0  
ca-certificates           2017.08.26           h1d4fec5_0  
cached-property           1.3.0                     <pip>
cairo                     1.14.8                        0  
cffi                      1.10.0                   py36_0  
chardet                   3.0.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.9                    py36_0  
conda                     4.3.31                   py36_0  
conda-env                 2.6.0                h36134e3_1  
contextlib2               0.5.5                    py36_0  
cryptography              1.8.1                    py36_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.14.3                   py36_1  
datashape                 0.5.4                    py36_0  
db                        0.1.1                     <pip>
dbus                      1.10.10                       0  
decorator                 4.0.11                   py36_0  
defusedxml                0.5.0                     <pip>
distributed               1.16.3                   py36_0  
django                    1.11.3                   py36_0  
djangorestframework       3.7.3                     <pip>
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                    py36_1  
et_xmlfile                1.0.1                    py36_0  
expat                     2.1.0                         0  
fastcache                 1.0.2                    py36_1  
flask                     0.12.2                   py36_0  
flask-cors                3.0.2                    py36_0  
fontconfig                2.12.1                        3  
freetype                  2.5.5                         2  
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
glib                      2.50.2                        1  
greenlet                  0.4.12                   py36_0  
gst-plugins-base          1.8.0                         0  
gstreamer                 1.8.0                         0  
h5py                      2.7.0               np112py36_0  
harfbuzz                  0.9.39                        2  
hdf5                      1.8.17                        1  
heapdict                  1.0.0                    py36_1  
html5lib                  0.999                    py36_0  
icu                       54.1                          0  
idna                      2.5                      py36_0  
imagesize                 0.7.1                    py36_0  
ipykernel                 4.6.1                    py36_0  
ipython                   5.3.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
isodate                   0.5.4                     <pip>
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.10.2                   py36_2  
jinja2                    2.9.6                    py36_0  
jpeg                      9b                            0  
jsonschema                2.6.0                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            5.0.1                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
lazy-object-proxy         1.2.2                    py36_0  
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                         1  
libgcc                    4.8.5                         2  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran               3.0.0                         1  
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libsodium                 1.0.10                        0  
libstdcxx-ng              7.2.0                h7a57d05_2  
libtiff                   4.0.6                         3  
libtool                   2.4.2                         0  
libxcb                    1.12                          1  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.18.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.3                    py36_0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.2               np112py36_0  
mistune                   0.7.4                    py36_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
msgpack-python            0.4.8                    py36_0  
multidict                 3.1.3                     <pip>
multipledispatch          0.4.9                    py36_0  
navigator-updater         0.1.0                    py36_0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
ncurses                   6.0                  h9df7e31_2  
networkx                  1.11                     py36_0  
nltk                      3.2.3                    py36_0  
nose                      1.3.7                    py36_1  
notebook                  5.0.0                    py36_0  
numba                     0.33.0              np112py36_0  
numexpr                   2.6.2               np112py36_0  
numpy                     1.12.1                   py36_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
olefile                   0.44                     py36_0  
openpyxl                  2.4.7                    py36_0  
openssl                   1.0.2n               hb7f436b_0  
packaging                 16.8                     py36_0  
pandas                    0.20.1              np112py36_0  
pandocfilters             1.4.1                    py36_0  
pango                     1.40.3                        1  
partd                     0.3.8                    py36_0  
path.py                   10.3.1                   py36_0  
pathlib2                  2.2.1                    py36_0  
patsy                     0.4.1                    py36_0  
pcre                      8.39                          1  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.1.1                    py36_0  
pip                       9.0.1                    py36_1  
pixman                    0.34.0                        0  
ply                       3.10                     py36_0  
prompt_toolkit            1.0.14                   py36_0  
psutil                    5.2.2                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.33                   py36_0  
pycosat                   0.6.2                    py36_0  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_6  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.2.0                    py36_0  
pylint                    1.6.4                    py36_1  
pyodbc                    4.0.16                   py36_0  
pyopenssl                 17.0.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_2  
pytables                  3.3.0               np112py36_0  
pytest                    3.0.7                    py36_0  
python                    3.6.3                h6c0c0dc_5  
python-dateutil           2.6.0                    py36_0  
pytz                      2017.2                   py36_0  
pywavelets                0.5.2               np112py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         4  
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.3.0                    py36_0  
qtpy                      1.2.1                    py36_0  
readline                  7.0                  ha6073c6_4  
requests                  2.14.2                   py36_0  
requests-toolbelt         0.8.0                     <pip>
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.13.0              np112py36_0  
scikit-learn              0.18.1              np112py36_1  
scipy                     0.19.0              np112py36_0  
seaborn                   0.7.1                    py36_0  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
soaplib                   1.0.0                     <pip>
sortedcollections         0.5.3                    py36_0  
sortedcontainers          1.5.7                    py36_0  
sphinx                    1.5.6                    py36_0  
spyder                    3.1.4                    py36_0  
sqlalchemy                1.1.11                   py36_0  
sqlite                    3.20.1               hb898158_2  
statsmodels               0.8.0               np112py36_0  
sympy                     1.0                      py36_0  
tblib                     1.3.2                    py36_0  
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
tk                        8.6.7                hc745277_3  
toolz                     0.8.2                    py36_0  
tornado                   4.5.1                    py36_0  
traitlets                 4.3.2                    py36_0  
unicodecsv                0.14.1                   py36_0  
unixodbc                  2.3.4                         0  
utils                     0.9.0                     <pip>
wcwidth                   0.1.7                    py36_0  
werkzeug                  0.12.2                   py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        2.0.0                    py36_0  
wrapt                     1.10.10                  py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.3                h55aa19d_2  
yaml                      0.1.6                         0  
yarl                      0.12.0                    <pip>
zeep                      2.2.0                     <pip>
zeromq                    4.1.5                         0  
zict                      0.1.2                    py36_0  
zlib                      1.2.11               ha838bed_2  
dave@RUPC:~/DjangoProjects/anaconda_testing$ conda create -n myenv
Fetching package metadata ...........
Solving package specifications: 
Package plan for installation in environment /home/dave/anaconda3/envs/myenv:

Proceed ([y]/n)? y

#
# To activate this environment, use:
# > source activate myenv
#
# To deactivate an active environment, use:
# > source deactivate
#

dave@RUPC:~/DjangoProjects/anaconda_testing$ ^C
dave@RUPC:~/DjangoProjects/anaconda_testing$ source activate myenv
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ ls
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ conda list
# packages in environment at /home/dave/anaconda3/envs/myenv:
#

(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ 
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ python3 -V
Python 3.6.3 :: Anaconda custom (64-bit)
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ django -V
django: command not found
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ conda install -c anaconda django
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/dave/anaconda3/envs/myenv:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0    anaconda
    certifi:         2017.11.5-py36hf29ccca_0 anaconda
    django:          1.11.8-py36hd476221_0    anaconda
    libedit:         3.1-heed3624_0           anaconda
    libffi:          3.2.1-hd88cf55_4         anaconda
    libgcc-ng:       7.2.0-h7cc24e2_2         anaconda
    libstdcxx-ng:    7.2.0-h7a57d05_2         anaconda
    ncurses:         6.0-h9df7e31_2           anaconda
    openssl:         1.0.2n-hb7f436b_0        anaconda
    pip:             9.0.1-py36h6c6f9ce_4     anaconda
    python:          3.6.3-h6c0c0dc_5         anaconda
    pytz:            2017.3-py36h63b9c63_0    anaconda
    readline:        7.0-ha6073c6_4           anaconda
    setuptools:      36.5.0-py36he42e2e1_0    anaconda
    sqlite:          3.20.1-hb898158_2        anaconda
    tk:              8.6.7-hc745277_3         anaconda
    wheel:           0.30.0-py36hfd4bba0_1    anaconda
    xz:              5.2.3-h55aa19d_2         anaconda
    zlib:            1.2.11-ha838bed_2        anaconda

Proceed ([y]/n)? y

ca-certificate 100% |####################################################| Time: 0:00:00 348.04 kB/s
libgcc-ng-7.2. 100% |####################################################| Time: 0:00:03   1.62 MB/s
libstdcxx-ng-7 100% |####################################################| Time: 0:00:01   1.75 MB/s
libffi-3.2.1-h 100% |####################################################| Time: 0:00:00   5.43 MB/s
ncurses-6.0-h9 100% |####################################################| Time: 0:00:00   1.05 MB/s
openssl-1.0.2n 100% |####################################################| Time: 0:00:01   1.99 MB/s
tk-8.6.7-hc745 100% |####################################################| Time: 0:00:01   1.74 MB/s
xz-5.2.3-h55aa 100% |####################################################| Time: 0:00:00 947.08 kB/s
zlib-1.2.11-ha 100% |####################################################| Time: 0:00:00 334.30 kB/s
libedit-3.1-he 100% |####################################################| Time: 0:00:01 148.20 kB/s
readline-7.0-h 100% |####################################################| Time: 0:00:02 441.94 kB/s
sqlite-3.20.1- 100% |####################################################| Time: 0:00:01 908.27 kB/s
python-3.6.3-h 100% |####################################################| Time: 0:00:16   1.88 MB/s
certifi-2017.1 100% |####################################################| Time: 0:00:00 262.42 kB/s
pytz-2017.3-py 100% |####################################################| Time: 0:00:00 365.39 kB/s
django-1.11.8- 100% |####################################################| Time: 0:00:02   1.68 MB/s
setuptools-36. 100% |####################################################| Time: 0:00:00 528.83 kB/s
wheel-0.30.0-p 100% |####################################################| Time: 0:00:00 238.39 kB/s
pip-9.0.1-py36 100% |####################################################| Time: 0:00:02 928.35 kB/s
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ conda list
# packages in environment at /home/dave/anaconda3/envs/myenv:
#
ca-certificates           2017.08.26           h1d4fec5_0    anaconda
certifi                   2017.11.5        py36hf29ccca_0    anaconda
django                    1.11.8           py36hd476221_0    anaconda
libedit                   3.1                  heed3624_0    anaconda
libffi                    3.2.1                hd88cf55_4    anaconda
libgcc-ng                 7.2.0                h7cc24e2_2    anaconda
libstdcxx-ng              7.2.0                h7a57d05_2    anaconda
ncurses                   6.0                  h9df7e31_2    anaconda
openssl                   1.0.2n               hb7f436b_0    anaconda
pip                       9.0.1            py36h6c6f9ce_4    anaconda
python                    3.6.3                h6c0c0dc_5    anaconda
pytz                      2017.3           py36h63b9c63_0    anaconda
readline                  7.0                  ha6073c6_4    anaconda
setuptools                36.5.0           py36he42e2e1_0    anaconda
sqlite                    3.20.1               hb898158_2    anaconda
tk                        8.6.7                hc745277_3    anaconda
wheel                     0.30.0           py36hfd4bba0_1    anaconda
xz                        5.2.3                h55aa19d_2    anaconda
zlib                      1.2.11               ha838bed_2    anaconda
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ conda install -c anaconda djangorestframework
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:
            
  - djangorestframework

We have searched for the packages in the following channels:
            
  - https://conda.anaconda.org/anaconda/linux-64
  - https://conda.anaconda.org/anaconda/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
            

(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ conda config --add channels conda-forge
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ conda install djangorestframework
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/dave/anaconda3/envs/myenv:

The following NEW packages will be INSTALLED:

    djangorestframework: 3.7.3-py_0 conda-forge

Proceed ([y]/n)? y

djangorestfram 100% |####################################################| Time: 0:00:01 629.06 kB/s
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ conda list
# packages in environment at /home/dave/anaconda3/envs/myenv:
#
ca-certificates           2017.08.26           h1d4fec5_0    anaconda
certifi                   2017.11.5        py36hf29ccca_0    anaconda
django                    1.11.8           py36hd476221_0    anaconda
djangorestframework       3.7.3                      py_0    conda-forge
libedit                   3.1                  heed3624_0    anaconda
libffi                    3.2.1                hd88cf55_4    anaconda
libgcc-ng                 7.2.0                h7cc24e2_2    anaconda
libstdcxx-ng              7.2.0                h7a57d05_2    anaconda
ncurses                   6.0                  h9df7e31_2    anaconda
openssl                   1.0.2n               hb7f436b_0    anaconda
pip                       9.0.1            py36h6c6f9ce_4    anaconda
python                    3.6.3                h6c0c0dc_5    anaconda
pytz                      2017.3           py36h63b9c63_0    anaconda
readline                  7.0                  ha6073c6_4    anaconda
setuptools                36.5.0           py36he42e2e1_0    anaconda
sqlite                    3.20.1               hb898158_2    anaconda
tk                        8.6.7                hc745277_3    anaconda
wheel                     0.30.0           py36hfd4bba0_1    anaconda
xz                        5.2.3                h55aa19d_2    anaconda
zlib                      1.2.11               ha838bed_2    anaconda
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ django-admin.py startproject testproj .
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ cd testproj
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing/testproj$ django-admin.py startapp quickstart
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing/testproj$ cd ..
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ pwd
/home/dave/DjangoProjects/anaconda_testing
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ find .
.
./manage.py
./testproj
./testproj/settings.py
./testproj/__init__.py
./testproj/quickstart
./testproj/quickstart/tests.py
./testproj/quickstart/migrations
./testproj/quickstart/migrations/__init__.py
./testproj/quickstart/models.py
./testproj/quickstart/admin.py
./testproj/quickstart/apps.py
./testproj/quickstart/__init__.py
./testproj/quickstart/views.py
./testproj/urls.py
./testproj/wsgi.py
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying sessions.0001_initial... OK
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ python3 manage.py createsuperuser
Username (leave blank to use 'dave'): admin
Email address: abc@123.com
Password: 
Password (again): 
Superuser created successfully.
(myenv) dave@RUPC:~/DjangoProjects/anaconda_testing$ source deactivate
dave@RUPC:~/DjangoProjects/anaconda_testing$ cd ..
dave@RUPC:~/DjangoProjects$ ls
anaconda_testing  dj_rest_framework
dave@RUPC:~/DjangoProjects$ cd dj_rest_framework
dave@RUPC:~/DjangoProjects/dj_rest_framework$ ls
CreationDoc.txt  projectSetupSheet.txt  tutorial
dave@RUPC:~/DjangoProjects/dj_rest_framework$ cd tutorial
dave@RUPC:~/DjangoProjects/dj_rest_framework/tutorial$ ls
dave@RUPC:~/DjangoProjects/dj_rest_framework/tutorial$ conda -V
conda 4.3.31
dave@RUPC:~/DjangoProjects/dj_rest_framework/tutorial$ 

